name: Generate Snake Game GIF

on:
  # Runs once every day at 08:00 UTC (a good time to catch new contributions)
  schedule:
    - cron: "0 8 * * *" 
  
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository code
      - uses: actions/checkout@v4
      
      # Step 2: Generates the snake animation 
      - uses: Platane/snk@v3
        with:
          # Your GitHub user name, used to fetch the contribution graph
          github_user_name: Dushani-Ekanayake 

          # The GitHub token is automatically provided for permissions
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          
          # Defines the output files and commits them back to the 'output' branch
          outputs: |
            # Standard SVG format for the animation
            dist/github-snake.svg 
            
            # GIF format, optimized for dark mode (like your profile)
            dist/github-snake-dark.gif?color_snake=#2d3039&color_dots=#40c463
            
            # SVG format for dark mode
            dist/github-snake-dark.svg

      # Step 3: Pushes the newly created GIF/SVG files to a separate 'output' branch
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # This is the branch where the files are stored
          build_dir: dist       # This is the folder containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
